apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: go-app
  template:
    containers:
    - name: go-app
      image: shrikolli/kube-app-107
      ports:
        - contianerPort: 80